"""notification types

Revision ID: 90cee9543b1e
Revises: 132fde0b6f4b
Create Date: 2019-07-30 19:05:25.845688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cee9543b1e'
down_revision = '132fde0b6f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'type')
    # ### end Alembic commands ###
